[package]
name = "wasm-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ab_glyph = "0.2.28"
glyph_brush = "0.7.10"
image = "0.25.2"
imageproc = "0.25.0"
js-sys = "0.3.70"
wasm-bindgen = "0.2.93"